# Generated by Django 4.1.2 on 2022-10-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('extra', models.CharField(default='NONE', max_length=6)),
                ('set', models.CharField(max_length=5)),
                ('collector_number', models.IntegerField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
