# Generated by Django 4.1.2 on 2022-10-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardRepository', '0002_alter_card_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueSpells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(default=1)),
                ('extra', models.CharField(default='NONE', max_length=6)),
                ('set', models.CharField(max_length=5)),
                ('collector_number', models.IntegerField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Bulk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(default=1)),
                ('extra', models.CharField(default='NONE', max_length=6)),
                ('set', models.CharField(max_length=5)),
                ('collector_number', models.IntegerField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ColorlessSpells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(default=1)),
                ('extra', models.CharField(default='NONE', max_length=6)),
                ('set', models.CharField(max_length=5)),
                ('collector_number', models.IntegerField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='GreenSpells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(default=1)),
                ('extra', models.CharField(default='NONE', max_length=6)),
                ('set', models.CharField(max_length=5)),
                ('collector_number', models.IntegerField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(default=1)),
                ('extra', models.CharField(default='NONE', max_length=6)),
                ('set', models.CharField(max_length=5)),
                ('collector_number', models.IntegerField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(default=1)),
                ('extra', models.CharField(default='NONE', max_length=6)),
                ('set', models.CharField(max_length=5)),
                ('collector_number', models.IntegerField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='MulticolorSpells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(default=1)),
                ('extra', models.CharField(default='NONE', max_length=6)),
                ('set', models.CharField(max_length=5)),
                ('collector_number', models.IntegerField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Planeswalker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(default=1)),
                ('extra', models.CharField(default='NONE', max_length=6)),
                ('set', models.CharField(max_length=5)),
                ('collector_number', models.IntegerField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='RedSpells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(default=1)),
                ('extra', models.CharField(default='NONE', max_length=6)),
                ('set', models.CharField(max_length=5)),
                ('collector_number', models.IntegerField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteSpells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(default=1)),
                ('extra', models.CharField(default='NONE', max_length=6)),
                ('set', models.CharField(max_length=5)),
                ('collector_number', models.IntegerField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RenameModel(
            old_name='Card',
            new_name='BlackSpells',
        ),
    ]
